/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Dex } from "./Dex";
export type { ERC20 } from "./ERC20";

export { Dex__factory } from "./factories/Dex__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
